"""Spatial XRF mapping: element maps, line scans, and project containers."""

from core.mapping.models import (
    ElementMap,
    OverviewImage,
    MapSpectrum,
    LineScan,
    MappingFOV,
    MappingSample,
    MappingProject,
    coerce_element_symbols,
)
from core.mapping.merge import (
    composite_label,
    merge_ipj_line_scans,
    merge_line_scan_projects,
    sanitize_name_token,
)
from core.mapping.cube import SpectrumCube, decode_listdata
from core.mapping.profiles import (
    extract_cube_element_profiles,
    extract_line_profile,
    extract_multi_element_profiles,
    line_distances,
)
from core.mapping.camera import StageCamera, camera_from_image, locate_image_crop, locate_red_map_rect, locate_scaled_template, camera_from_sample_sites, calibrate_stage_camera
from core.mapping.correlations import map_correlation, map_correlation_matrix, rgb_composite
from core.mapping.display import (
    enhance_map,
    format_acquisition,
    upsample_map,
    overlay_on_photo,
    overlay_alpha,
    colorize_map,
    resize_to,
    embed_map_on_photo,
    apply_contrast,
    ratio_map,
    difference_map,
    bilateral_filter,
)
from core.mapping.multivariate import (
    PCAResult,
    Particle,
    ParticleResult,
    pca_element_maps,
    find_particles,
    particle_label_map_as_element,
)
from core.mapping.regions import circle_mask, polygon_mask, rect_mask, region_mask

__all__ = [
    "ElementMap",
    "OverviewImage",
    "MapSpectrum",
    "LineScan",
    "MappingFOV",
    "MappingSample",
    "MappingProject",
    "coerce_element_symbols",
    "composite_label",
    "merge_ipj_line_scans",
    "merge_line_scan_projects",
    "sanitize_name_token",
    "SpectrumCube",
    "decode_listdata",
    "StageCamera",
    "camera_from_image",
    "camera_from_sample_sites",
    "calibrate_stage_camera",
    "locate_image_crop",
    "locate_scaled_template",
    "locate_red_map_rect",
    "extract_line_profile",
    "extract_multi_element_profiles",
    "extract_cube_element_profiles",
    "line_distances",
    "map_correlation",
    "map_correlation_matrix",
    "rgb_composite",
    "enhance_map",
    "format_acquisition",
    "upsample_map",
    "resize_to",
    "colorize_map",
    "overlay_alpha",
    "overlay_on_photo",
    "embed_map_on_photo",
    "apply_contrast",
    "ratio_map",
    "difference_map",
    "bilateral_filter",
    "PCAResult",
    "Particle",
    "ParticleResult",
    "pca_element_maps",
    "find_particles",
    "particle_label_map_as_element",
    "rect_mask",
    "circle_mask",
    "polygon_mask",
    "region_mask",
]
